---
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(lubridate)
library(pins)
library(tidymodels)
library(patchwork)
library(recipes)
library(embed)
library(corrplot)
library(dbscan)
library(wesanderson)

# Load the data
target_file = "team_summary"
df <- readRDS(paste0("clean_data/", target_file, ".rds"))

get_test_results <- function(
  model,
  test
){
  test_x = test %>% select(-Y)
  test_y = test %>% pull(Y)
  test_prediction = predict(model, new_data = test_x)
  test_results = test %>% 
    select(Y) %>% 
    bind_cols(
      test_prediction
    )
  
  if(".pred" %in% names(test_results)){
    test_results <- test_results %>% 
      rename(
        "Predicted" = ".pred",
        "Observed" = "Y"
      )
  }else if(".pred_res" %in% names(test_results)){
    test_results <- test_results %>% 
      rename(
        "Predicted" = ".pred_res",
        "Observed" = "Y"
      )
  }else if(".pred_class" %in% names(test_results)){
    test_results <- test_results %>% 
      rename(
        "Predicted" = ".pred_class",
        "Observed" = "Y"
      )
  }
  
  return(test_results)
}

get_train_results <- function(
  model,
  train
){
  train_x = train %>% select(-Y)
  train_y = train %>% pull(Y)
  train_prediction = predict(model, new_data = train_x)
  train_results = train %>% 
    select(Y) %>% 
    bind_cols(
      train_prediction
    )
  
  if(".pred" %in% names(train_results)){
    train_results <- train_results %>% 
      rename(
        "Predicted" = ".pred",
        "Observed" = "Y"
      )
  }else if(".pred_res" %in% names(train_results)){
    train_results <- train_results %>% 
      rename(
        "Predicted" = ".pred_res",
        "Observed" = "Y"
      )
  }else if(".pred_class" %in% names(test_results)){
    test_results <- test_results %>% 
      rename(
        "Predicted" = ".pred_class",
        "Observed" = "Y"
      )
  }
  
  return(train_results)
}

# Evaluate Model
evaluate_model <- function(
  model,
  train,
  test
){
  train_results = get_train_results(model, train)
  test_results = get_test_results(model, test)
  results <- train_results %>% 
    mutate(Case = "Train") %>% 
    bind_rows(
      test_results %>% 
        mutate(Case = "Test")
    )
  
  if("factor" %in% class(results$Predicted)){
    # train_matrix <- train_results %>% 
    #   mutat
    # TODO: Plot this instead as two matrices of correspondence between predicted and observed
    return()
  }else{
    limit = c(min(c(results$Predicted, results$Observed), na.rm = T), max(c(results$Predicted, results$Observed), na.rm = T))
  
    gg <- results %>% 
      ggplot(
        aes(
          x = Predicted,
          y = Observed,
          colour = Case,
          alpha = Case
        )
      ) + 
      geom_point(na.rm = T) + 
      theme_bw(12) + 
      geom_abline(slope = 1, intercept = 0) + 
      scale_colour_manual(values = c("Train" = "grey", "Test" = "blue")) + 
      scale_alpha_manual(values = c("Train" = 0.2, "Test" = 0.5)) + 
      ylim(limit) + 
      xlim(limit)
  }
  
  return(gg)
}

# Initial filtering and manipulation
## TODO

## Force some variables to be factor
# df <- df %>% 
#   mutate_at(
#     vars(),
#     factor
#   )

## Some preprocessing


# Columns to be intentionally excluded entirely, in all cases
dropped_columns = c(
  
)

# Potential response columns (will generally only consider one at a time)
response_columns = c(
  
)

# Columns potentially removed in some cases (separated for simple commenting out)
screened_columns = c(
  
)

## not_considered_columns are any columns that will be removed
not_considered_columns = c(dropped_columns, screened_columns, response_columns)

## considered_columns will always include any remaining columns, and a special column "Y"
considered_columns = names(df)[!(names(df) %in% not_considered_columns)]
considered_columns = c(considered_columns, "Y")

# General purpose preprocessing function
preprocess <- function(
  df, 
  response = NULL, 
  predictors = considered_columns, 
  drop_at_na_level = 0.99, 
  max_categorical_levels = 50,
  na.rm = T
){
  X = df

  if(!is.null(response)){
    # Filter out any NA in the response
    X = X[!is.na(X[[response]]), ]
  }
  
  # Drop columns with too many NAs
  ## This is specified by the "drop_at_na_level" parameter, where only columns with at least that fraction non-na will be retained
  not_too_many_na = function(x, threshold = 1 - drop_at_na_level){
    n_na = sum(is.na(x))
    n = length(x)
    return(
      (n_na/n) <= threshold
    )
  }
  X <- X %>% select(where(not_too_many_na))
  
  if(na.rm){
    # Drop NA rows
    X <- na.omit(X)
  }
  
  # Drop columns with too many (or not enough) categorical variables
  not_too_many_categorical = function(x, threshold = max_categorical_levels){
    if(!is.character(x)){
      return(TRUE)
    }else{
      n = length(unique(x))
      if(!is.null(threshold)){
        return(n <= threshold & n >= 2)
      }else{
        return(n >= 2)
      }
    }
  }
  X <- X %>% select(where(not_too_many_categorical))
  
  if(!is.null(response)){
    # Rename the response
    names(X)[names(X) == response] <- "Y"
  }else{
    # Do nothing
  }
  
  # Factorise X
  X <- X %>% 
    mutate_if(
      is.character,
      as.factor
    )
  
  if(!is.null(predictors)){
    # Drop irrelevant variables
    # cat(paste0('"', paste0(names(X), collapse = '",\n"'), '"'))
    X_ <- X[, -which(names(X) %in% predictors)]
    X <- X[, which(names(X) %in% predictors)]
  }else{
    X_ <- X[,NULL]
  }
  
  return(
    list(
      "main" = X,
      "secondary" = X_,
      "response" = response
    )
  )
}

# Set the default for random forest
rf_defaults <- rand_forest(mode = "classification")

# Set the default response column
RESPONSE = NULL
```

# Initial Screening of Variables
```{r}
X_total <- df %>% preprocess(response = RESPONSE, predictors = considered_columns)
X <- X_total$main

summary(X)
```

## Numerical Variable Correlations
```{r fig.width=10, fig.height=10}
X_total <- df %>% preprocess(response = RESPONSE, predictors = c(considered_columns, response_columns, screened_columns))
X <- X_total$main

corrmat <- X %>% 
  select(where(is.numeric)) %>% 
  cor()

png(filename = "plots/team_corrplot.png", width = 3500, height = 3500)
corrplot(corrmat, type = "upper", order = "hclust", tl.col = "black", tl.srt = 90, tl.cex = 0.8)
dev.off()

corrplot(corrmat, type = "upper", order = "hclust", tl.col = "black", tl.srt = 90, tl.cex = 0.8)
```

# HClust
```{r fig.width=10, fig.height=10}
X_total <- df %>% preprocess(response = RESPONSE, predictors = c(considered_columns, response_columns, screened_columns))
X <- X_total$main

corrmat <- X %>% 
  select(where(is.numeric)) %>% 
  cor()

png(filename = "plots/team_hclust.png", width = 3500, height = 500)
plot(hclust(as.dist(1-corrmat)))
dev.off()

plot(hclust(as.dist(1-corrmat)))
```

# UMAP Investigation (Unsupervised)
```{r}
# Get the dataset
X_total <- df %>% preprocess(response = RESPONSE, predictors = c(considered_columns))
X <- X_total$main

# Determine which columns are factors (needing to be one-hot-encoded)
factors = X %>% 
  select(where(is.factor)) %>% 
  names()

# Leave the response variable as-is
factors <- factors[factors != "Y"]

train = X

unsupervised <- recipe(~ ., data = train) %>% 
  step_dummy(all_of(factors), one_hot = T)
  # step_center(all_predictors()) %>% 
  # step_scale(all_predictors())

unsupervised %>% prep(training = train) %>% summary()
```

```{r}
umap_2 = unsupervised %>% 
  step_umap(all_predictors(), num_comp = 2, retain = F) %>%
  prep(training = train)

umap_2_train <- bake(
  umap_2,
  new_data = train
) 

summary(umap_2_train)
```


```{r fig.width=10, fig.height=6}
umap_2_train_plot <- umap_2_train %>% 
  bind_cols(X) %>% 
  ggplot(
    aes(
      x = umap_1,
      y = umap_2,
      colour = ZONE_LOGICAL_AFL
    )
  ) + 
  geom_point(alpha = 0.3, size = 0.1) + 
  theme_bw(12)

# umap_2_train_plot %>% plotly::ggplotly()
umap_2_train_plot
```

## Extract Clusters with HDBSCAN
```{r}
# Get 5-dimensional representation of dataset
umap_5_train = unsupervised %>% 
  step_umap(all_predictors(), num_comp = 5, retain = F) %>%
  prep(training = train) %>% 
  bake(new_data = train)

summary(umap_5_train)
```


```{r, fig.width=10, fig.height=6}
# Execute the hdbscan algorithm
cluster = umap_5_train %>% as.matrix() %>% hdbscan(minPts = 40, gen_hdbscan_tree = T, gen_simplified_tree = T)

message(paste0("Number of Clusters: ", length(unique(cluster$cluster) - 1)))
message(paste0("Outlier Proportion: ", signif(sum(cluster$cluster == 0) / length(cluster$cluster), 3)))

tibble(
  Cluster = cluster$cluster
) %>% 
  group_by(Cluster) %>% 
  count() %>% 
  ungroup() %>% 
  arrange(desc(n)) %>% 
  print()

plot(cluster, show_flat = T)
```

## Overlay on 2D UMAP output
```{r}
umap_2_cluster <- umap_2_train %>% 
  mutate(Cluster = cluster$cluster)

umap_2_cluster_plot <- umap_2_cluster %>% 
  mutate(
    Cluster = factor(Cluster)
  ) %>% 
  ggplot(
    aes(
      x = umap_1,
      y = umap_2,
      col = Cluster
    )
  ) + 
  geom_point(alpha = 0.3, size = 0.1) + 
  theme_bw(12)

# umap_2_cluster_plot %>% plotly::ggplotly()
umap_2_cluster_plot
```

## Random Forest (predicting cluster)
```{r}
umap_2_all <- umap_2_train %>% 
  mutate(Cluster = cluster$cluster) %>% 
  bind_cols(train)

X_total <- umap_2_all %>% 
  mutate(
    Cluster = factor(Cluster)
  ) %>% 
  preprocess(response = "Cluster", predictors = considered_columns)
X <- X_total$main

data_split <- initial_split(X, strata = "Y", p = 0.8)
train = training(data_split)
test = testing(data_split)

train_x = train %>% select(-Y)
train_y = train %>% pull(Y)

rf <- rf_defaults %>% 
  set_engine("ranger", importance = "impurity") %>% 
  fit_xy(
    x = train_x,
    y = train_y
  )
  
# Summarise performance
get_test_results(rf, test) %>% metrics(truth = Observed, estimate = Predicted)
```

```{r}
# Predicted vs Observed
evaluate_model(rf, train, test)
```

```{r fig.width=10, fig.height=20}
imp <- rf$fit$variable.importance
imp <- tibble(
  Variable = names(imp),
  Importance = imp
) %>% 
  arrange(
    desc(Importance)
  ) %>% 
  mutate(
    Variable = factor(Variable, levels = Variable, ordered = T)
  )

imp_rev <- imp %>% 
  arrange(
    Importance
  ) %>% 
  mutate(
    Variable = factor(Variable, levels = Variable, ordered = T)
  )

imp_rev %>% 
  head(100) %>%
  ggplot(
    aes(
      x = Variable,
      y = Importance
    )
  ) + 
  geom_bar(stat = 'identity', na.rm = T) + 
  coord_flip() + 
  theme_bw(12)
```

## What is "EXPECTED_SCORE"?
```{r fig.width=10, fig.height=6, include=F}
plot(
X %>% 
  ggplot(
    aes(
      x = SCORING_SHOTS,
      y = EXPECTED_SCORE
    )
  ) + 
  geom_point() + 
  theme_bw()
)

m <- lm(EXPECTED_SCORE ~ SCORING_SHOTS, data = X)
print(summary(m))
```


Plot the top 100 influences:
```{r fig.width=15, fig.height=8}
i = 1
i_max = 100
# for(var in imp$Variable){
for(i in 1:100){
  if(i <= i_max){
    var = imp$Variable[i]
    
    dt = tibble(
      X = X[[var]],
      Y = !!X$Y,
      Game = !!X_total$main$MATCH_ID
    )
    
    corr_plot = dt %>% 
      ggplot(
        aes(
          x = X,
          y = Y
        )
      ) + 
      theme_bw(12) + 
      xlab(var) + 
      ylab(X_total$response)
    # + 
    #   geom_smooth(method = "lm", linetype = "dashed", formula = y ~ x)
    
    if(is.factor(dt$X)){
      corr_plot <- corr_plot + geom_jitter(na.rm = T, size = 0.1, alpha = 0.3, height = 0.25)
    }else{
      corr_plot <- corr_plot + geom_jitter(na.rm = T, size = 0.1, alpha = 0.3, height = 0.25, width = 0)
    }
    
    game_plot = dt %>% 
      ggplot(
        aes(
          x = Game,
          colour = Y,
          y = X
        )
      ) + 
      geom_point(na.rm=T, size = 0.5, alpha = 0.4) + 
      theme_bw(12) + 
      xlab("Game") + 
      ylab(var) + 
      theme(
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank()
      )
    
    umap_overlay_plot <- umap_2_all %>% 
      mutate(
        Cluster = factor(Cluster)
      ) %>% 
      ggplot(
        aes_string(
          x = "umap_1",
          y = "umap_2",
          colour = as.character(var)
        )
      ) + 
      geom_point(alpha = 0.3, size = 0.1) + 
      theme_bw(12) + 
      ggtitle(var) + 
      theme(
        axis.title.x=element_blank(),
        axis.text.x=element_blank(),
        axis.ticks.x=element_blank(),
        axis.title.y=element_blank(),
        axis.text.y=element_blank(),
        axis.ticks.y=element_blank(),
        legend.title=element_blank()
      )
    
    if(!("factor" %in% class(umap_2_all[[var]]))){
      umap_overlay_plot <- umap_overlay_plot + 
        scale_colour_gradientn(colours = wes_palette("Zissou1", type = "continuous"))
    }
    
    plot(umap_overlay_plot + (corr_plot / game_plot))
  }
}
```